### ISSUE TITLE
Version 2.1 of the module exists are these instructions relevant

### ISSUE THREAD

**Issue by AddictArts** [cannawen/vassal-gloomhaven-instructions#2]
Hi,

Thanks for the instructions. I'm very new to Gloomhaven, so apologies for anything due to that. I noticed the newer module, how do the instructions apply? Also, the extension versions are kinda confusing, what works with what? If I could add this info I would give you a pull request. I'm learning, so maybe I will figure it out. Cheers

**Comment by g4ttsu** [comment]
Hi,

that would be great. I am thinking about to add the instructions into the vassal wiki page. So if you have any changes and ideas of improvements pls let me know.

Best
Christoph

**Comment by cannawen** [comment]
I updated instructions to v2.2, I assume v2.1 is very similar. Closing issue.

**Comment by AddictArts** [comment]
I finally was able to follow along with these, thanks for updating them. While the instructions are great, the Vassal module is not for new comers, there is no hand holding, which is to be expected.
